improve clarification between communication modes
Southampton-RSG-Training/dirac-intro-to-mpi pull request #50
Opened 2024-07-23 12:34 UTC by Edward-RSE

This makes changes to the "Communicating Data" episode, which improves the clarity of the description of the different communication modes. I've explained in more depth why different modes exists, what they do and when best to use them, and finally some real life analogies.

I've opened this PR to get feedback before it is merged into the main branch.

2024-07-24 16:16 UTC, Edward-RSE commented
This PR now addresses issue #30 and issue #35.

2024-07-25 13:56 UTC, steve-crouch requested changes
Looks good, and I think reads much easier! Just a few very minor corrections and a question.

2024-07-25 13:56 UTC, steve-crouch commented on _episodes/03-communicating-data.md
> +don't automatically send and receive data. If we don't program in data communication, data isn'. Unfortunately,
Incomplete sentence, perhaps:

```suggestion
don't automatically send and receive data. If we don't program in data communication, data isn't exchanged. Unfortunately,

```

2024-07-25 13:56 UTC, steve-crouch commented on _episodes/03-communicating-data.md
> +> of points. How would you use calculate the average temperature?
```suggestion
> of points. How would you calculate the average temperature?

```

2024-07-25 13:56 UTC, steve-crouch commented on _episodes/03-communicating-data.md
> +> > If you weren't do this in parallel, or instead using shared-memory parallelism, you wouldn't need to do any
Perhaps add OpenMP as an example of shared memory parallelism, e.g. "...(e.g. using OpenMP)..."?

2024-07-25 13:56 UTC, steve-crouch commented on _episodes/03-communicating-data.md
> +topology](https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report/node192.htm#Node192). Throughout this lesson, we will
Could we not say "throughout this course" instead? (At least, as long as we don't use any other type of communicator?)

2024-07-25 13:56 UTC, steve-crouch commented on _episodes/03-communicating-data.md
> +data before it is send! This would lead to some very strange behaviour which would be very hard to debug. The difference
```suggestion
data before it is sent! This would lead to some very strange behaviour which would be very hard to debug. The difference

```

2024-07-25 13:56 UTC, steve-crouch commented on _episodes/05-collective-communication.md
> +a lot of code to do not much, which makes it easy to introduce mistakes in our code. Another mistake in this example
```suggestion
a lot of code to not do very much, which makes it easy to introduce mistakes in our code. Another mistake in this example

```

2024-07-25 13:56 UTC, steve-crouch commented on _episodes/05-collective-communication.md
> +MPI users to write something like above.
```suggestion
MPI users to write something like the above.

```

2024-07-25 14:16 UTC, Edward-RSE commented
Something seems to have broken with the review, as I've accepted your changes but the review isn't going away..

2024-07-26 09:41 UTC, merged